import type { Metadata } from "next";
import { Pacifico } from "next/font/google";

import "./globals.css";


const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});



export const metadata: Metadata = {
  title: "Simra Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pacifico.variable} antialiased fade-in`}>
       

        {children}

     
      </body>
    </html>
  );
}
